from table_scrapper import get_table

# --- Define one object (page_map) mapping each page to its tables ---
page_map = {
    "https://fbref.com/en/squads/18bb7c10/Arsenal-Stats": {
        "stats_standard_9": "arsenal_player_stats_standard",
        "matchlogs_for": "arsenal_match_logs_schedule",
        "stats_keeper_9": "arsenal_goalkeeping",
        "stats_keeper_adv_9": "arsenal_adv_goalkeeping",
        "stats_shooting_9": "arsenal_shooting_stats",
        "stats_passing_9": "arsenal_passing_stats",
        "stats_passing_types_9": "arsenal_passing_types_stats",
        "stats_gca_9": "arsenal_goal_creation_stats",
        "stats_defense_9": "arsenal_player_defensive_actions_stats",
        "stats_possession_9": "arsenal_player_possession_stats",
        "stats_playing_time_9": "arsenal_playing_time_stats",
        "stats_misc_9": "arsenal_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/8602292d/Aston-Villa-Stats": {
        "stats_standard_9": "aston_villa_player_stats_standard",
        "matchlogs_for": "aston_villa_match_logs_schedule",
        "stats_keeper_9": "aston_villa_goalkeeping",
        "stats_keeper_adv_9": "aston_villa_adv_goalkeeping",
        "stats_shooting_9": "aston_villa_shooting_stats",
        "stats_passing_9": "aston_villa_passing_stats",
        "stats_passing_types_9": "aston_villa_passing_types_stats",
        "stats_gca_9": "aston_villa_goal_creation_stats",
        "stats_defense_9": "aston_villa_player_defensive_actions_stats",
        "stats_possession_9": "aston_villa_player_possession_stats",
        "stats_playing_time_9": "aston_villa_playing_time_stats",
        "stats_misc_9": "aston_villa_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/4ba7cbea/Bournemouth-Stats": {
        "stats_standard_9": "bournemouth_player_stats_standard",
        "matchlogs_for": "bournemouth_match_logs_schedule",
        "stats_keeper_9": "bournemouth_goalkeeping",
        "stats_keeper_adv_9": "bournemouth_adv_goalkeeping",
        "stats_shooting_9": "bournemouth_shooting_stats",
        "stats_passing_9": "bournemouth_passing_stats",
        "stats_passing_types_9": "bournemouth_passing_types_stats",
        "stats_gca_9": "bournemouth_goal_creation_stats",
        "stats_defense_9": "bournemouth_player_defensive_actions_stats",
        "stats_possession_9": "bournemouth_player_possession_stats",
        "stats_playing_time_9": "bournemouth_playing_time_stats",
        "stats_misc_9": "bournemouth_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/cd051869/Brentford-Stats": {
        "stats_standard_9": "brentford_player_stats_standard",
        "matchlogs_for": "brentford_match_logs_schedule",
        "stats_keeper_9": "brentford_goalkeeping",
        "stats_keeper_adv_9": "brentford_adv_goalkeeping",
        "stats_shooting_9": "brentford_shooting_stats",
        "stats_passing_9": "brentford_passing_stats",
        "stats_passing_types_9": "brentford_passing_types_stats",
        "stats_gca_9": "brentford_goal_creation_stats",
        "stats_defense_9": "brentford_player_defensive_actions_stats",
        "stats_possession_9": "brentford_player_possession_stats",
        "stats_playing_time_9": "brentford_playing_time_stats",
        "stats_misc_9": "brentford_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats": {
        "stats_standard_9": "brighton_player_stats_standard",
        "matchlogs_for": "brighton_match_logs_schedule",
        "stats_keeper_9": "brighton_goalkeeping",
        "stats_keeper_adv_9": "brighton_adv_goalkeeping",
        "stats_shooting_9": "brighton_shooting_stats",
        "stats_passing_9": "brighton_passing_stats",
        "stats_passing_types_9": "brighton_passing_types_stats",
        "stats_gca_9": "brighton_goal_creation_stats",
        "stats_defense_9": "brighton_player_defensive_actions_stats",
        "stats_possession_9": "brighton_player_possession_stats",
        "stats_playing_time_9": "brighton_playing_time_stats",
        "stats_misc_9": "brighton_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/943e8050/Burnley-Stats": {
        "stats_standard_9": "burnley_player_stats_standard",
        "matchlogs_for": "burnley_match_logs_schedule",
        "stats_keeper_9": "burnley_goalkeeping",
        "stats_keeper_adv_9": "burnley_adv_goalkeeping",
        "stats_shooting_9": "burnley_shooting_stats",
        "stats_passing_9": "burnley_passing_stats",
        "stats_passing_types_9": "burnley_passing_types_stats",
        "stats_gca_9": "burnley_goal_creation_stats",
        "stats_defense_9": "burnley_player_defensive_actions_stats",
        "stats_possession_9": "burnley_player_possession_stats",
        "stats_playing_time_9": "burnley_playing_time_stats",
        "stats_misc_9": "burnley_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats": {
        "stats_standard_9": "chelsea_player_stats_standard",
        "matchlogs_for": "chelsea_match_logs_schedule",
        "stats_keeper_9": "chelsea_goalkeeping",
        "stats_keeper_adv_9": "chelsea_adv_goalkeeping",
        "stats_shooting_9": "chelsea_shooting_stats",
        "stats_passing_9": "chelsea_passing_stats",
        "stats_passing_types_9": "chelsea_passing_types_stats",
        "stats_gca_9": "chelsea_goal_creation_stats",
        "stats_defense_9": "chelsea_player_defensive_actions_stats",
        "stats_possession_9": "chelsea_player_possession_stats",
        "stats_playing_time_9": "chelsea_playing_time_stats",
        "stats_misc_9": "chelsea_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats": {
        "stats_standard_9": "crystal_palace_player_stats_standard",
        "matchlogs_for": "crystal_palace_match_logs_schedule",
        "stats_keeper_9": "crystal_palace_goalkeeping",
        "stats_keeper_adv_9": "crystal_palace_adv_goalkeeping",
        "stats_shooting_9": "crystal_palace_shooting_stats",
        "stats_passing_9": "crystal_palace_passing_stats",
        "stats_passing_types_9": "crystal_palace_passing_types_stats",
        "stats_gca_9": "crystal_palace_goal_creation_stats",
        "stats_defense_9": "crystal_palace_player_defensive_actions_stats",
        "stats_possession_9": "crystal_palace_player_possession_stats",
        "stats_playing_time_9": "crystal_palace_playing_time_stats",
        "stats_misc_9": "crystal_palace_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/d3fd31cc/Everton-Stats": {
        "stats_standard_9": "everton_player_stats_standard",
        "matchlogs_for": "everton_match_logs_schedule",
        "stats_keeper_9": "everton_goalkeeping",
        "stats_keeper_adv_9": "everton_adv_goalkeeping",
        "stats_shooting_9": "everton_shooting_stats",
        "stats_passing_9": "everton_passing_stats",
        "stats_passing_types_9": "everton_passing_types_stats",
        "stats_gca_9": "everton_goal_creation_stats",
        "stats_defense_9": "everton_player_defensive_actions_stats",
        "stats_possession_9": "everton_player_possession_stats",
        "stats_playing_time_9": "everton_playing_time_stats",
        "stats_misc_9": "everton_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/fd962109/Fulham-Stats": {
        "stats_standard_9": "fulham_player_stats_standard",
        "matchlogs_for": "fulham_match_logs_schedule",
        "stats_keeper_9": "fulham_goalkeeping",
        "stats_keeper_adv_9": "fulham_adv_goalkeeping",
        "stats_shooting_9": "fulham_shooting_stats",
        "stats_passing_9": "fulham_passing_stats",
        "stats_passing_types_9": "fulham_passing_types_stats",
        "stats_gca_9": "fulham_goal_creation_stats",
        "stats_defense_9": "fulham_player_defensive_actions_stats",
        "stats_possession_9": "fulham_player_possession_stats",
        "stats_playing_time_9": "fulham_playing_time_stats",
        "stats_misc_9": "fulham_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats": {
        "stats_standard_9": "leeds_united_player_stats_standard",
        "matchlogs_for": "leeds_united_match_logs_schedule",
        "stats_keeper_9": "leeds_united_goalkeeping",
        "stats_keeper_adv_9": "leeds_united_adv_goalkeeping",
        "stats_shooting_9": "leeds_united_shooting_stats",
        "stats_passing_9": "leeds_united_passing_stats",
        "stats_passing_types_9": "leeds_united_passing_types_stats",
        "stats_gca_9": "leeds_united_goal_creation_stats",
        "stats_defense_9": "leeds_united_player_defensive_actions_stats",
        "stats_possession_9": "leeds_united_player_possession_stats",
        "stats_playing_time_9": "leeds_united_playing_time_stats",
        "stats_misc_9": "leeds_united_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats": {
        "stats_standard_9": "manchester_city_player_stats_standard",
        "matchlogs_for": "manchester_city_match_logs_schedule",
        "stats_keeper_9": "manchester_city_goalkeeping",
        "stats_keeper_adv_9": "manchester_city_adv_goalkeeping",
        "stats_shooting_9": "manchester_city_shooting_stats",
        "stats_passing_9": "manchester_city_passing_stats",
        "stats_passing_types_9": "manchester_city_passing_types_stats",
        "stats_gca_9": "manchester_city_goal_creation_stats",
        "stats_defense_9": "manchester_city_player_defensive_actions_stats",
        "stats_possession_9": "manchester_city_player_possession_stats",
        "stats_playing_time_9": "manchester_city_playing_time_stats",
        "stats_misc_9": "manchester_city_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/19538871/Manchester-United-Stats": {
        "stats_standard_9": "manchester_united_player_stats_standard",
        "matchlogs_for": "manchester_united_match_logs_schedule",
        "stats_keeper_9": "manchester_united_goalkeeping",
        "stats_keeper_adv_9": "manchester_united_adv_goalkeeping",
        "stats_shooting_9": "manchester_united_shooting_stats",
        "stats_passing_9": "manchester_united_passing_stats",
        "stats_passing_types_9": "manchester_united_passing_types_stats",
        "stats_gca_9": "manchester_united_goal_creation_stats",
        "stats_defense_9": "manchester_united_player_defensive_actions_stats",
        "stats_possession_9": "manchester_united_player_possession_stats",
        "stats_playing_time_9": "manchester_united_playing_time_stats",
        "stats_misc_9": "manchester_united_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats": {
        "stats_standard_9": "newcastle_united_player_stats_standard",
        "matchlogs_for": "newcastle_united_match_logs_schedule",
        "stats_keeper_9": "newcastle_united_goalkeeping",
        "stats_keeper_adv_9": "newcastle_united_adv_goalkeeping",
        "stats_shooting_9": "newcastle_united_shooting_stats",
        "stats_passing_9": "newcastle_united_passing_stats",
        "stats_passing_types_9": "newcastle_united_passing_types_stats",
        "stats_gca_9": "newcastle_united_goal_creation_stats",
        "stats_defense_9": "newcastle_united_player_defensive_actions_stats",
        "stats_possession_9": "newcastle_united_player_possession_stats",
        "stats_playing_time_9": "newcastle_united_playing_time_stats",
        "stats_misc_9": "newcastle_united_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/e4a775cb/Nottingham-Forest-Stats": {
        "stats_standard_9": "nottingham_forest_player_stats_standard",
        "matchlogs_for": "nottingham_forest_match_logs_schedule",
        "stats_keeper_9": "nottingham_forest_goalkeeping",
        "stats_keeper_adv_9": "nottingham_forest_adv_goalkeeping",
        "stats_shooting_9": "nottingham_forest_shooting_stats",
        "stats_passing_9": "nottingham_forest_passing_stats",
        "stats_passing_types_9": "nottingham_forest_passing_types_stats",
        "stats_gca_9": "nottingham_forest_goal_creation_stats",
        "stats_defense_9": "nottingham_forest_player_defensive_actions_stats",
        "stats_possession_9": "nottingham_forest_player_possession_stats",
        "stats_playing_time_9": "nottingham_forest_playing_time_stats",
        "stats_misc_9": "nottingham_forest_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/8ef52968/Sunderland-Stats": {
        "stats_standard_9": "sunderland_player_stats_standard",
        "matchlogs_for": "sunderland_match_logs_schedule",
        "stats_keeper_9": "sunderland_goalkeeping",
        "stats_keeper_adv_9": "sunderland_adv_goalkeeping",
        "stats_shooting_9": "sunderland_shooting_stats",
        "stats_passing_9": "sunderland_passing_stats",
        "stats_passing_types_9": "sunderland_passing_types_stats",
        "stats_gca_9": "sunderland_goal_creation_stats",
        "stats_defense_9": "sunderland_player_defensive_actions_stats",
        "stats_possession_9": "sunderland_player_possession_stats",
        "stats_playing_time_9": "sunderland_playing_time_stats",
        "stats_misc_9": "sunderland_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats": {
        "stats_standard_9": "west_ham_player_stats_standard",
        "matchlogs_for": "west_ham_match_logs_schedule",
        "stats_keeper_9": "west_ham_goalkeeping",
        "stats_keeper_adv_9": "west_ham_adv_goalkeeping",
        "stats_shooting_9": "west_ham_shooting_stats",
        "stats_passing_9": "west_ham_passing_stats",
        "stats_passing_types_9": "west_ham_passing_types_stats",
        "stats_gca_9": "west_ham_goal_creation_stats",
        "stats_defense_9": "west_ham_player_defensive_actions_stats",
        "stats_possession_9": "west_ham_player_possession_stats",
        "stats_playing_time_9": "west_ham_playing_time_stats",
        "stats_misc_9": "west_ham_miscellaneous_stats",
    },
    "https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats": {
        "stats_standard_9": "wolverhampton_player_stats_standard",
        "matchlogs_for": "wolverhampton_match_logs_schedule",
        "stats_keeper_9": "wolverhampton_goalkeeping",
        "stats_keeper_adv_9": "wolverhampton_adv_goalkeeping",
        "stats_shooting_9": "wolverhampton_shooting_stats",
        "stats_passing_9": "wolverhampton_passing_stats",
        "stats_passing_types_9": "wolverhampton_passing_types_stats",
        "stats_gca_9": "wolverhampton_goal_creation_stats",
        "stats_defense_9": "wolverhampton_player_defensive_actions_stats",
        "stats_possession_9": "wolverhampton_player_possession_stats",
        "stats_playing_time_9": "wolverhampton_playing_time_stats",
        "stats_misc_9": "wolverhampton_miscellaneous_stats",
    },
    "https://fbref.com/en/comps/9/Premier-League-Stats": {
        "results2025-202691_overall": "premier_league_stats"
    },
    "https://fbref.com/en/comps/8/Champions-League-Stats":{
        "results2025-202682_overall": "ucl_champions_league_overall_1",
        "results2025-202680_overall": "ucl_champions_league_overall_2",
    },
    "https://fbref.com/en/comps/8/schedule/Champions-League-Scores-and-Fixtures":{
        "sched_all":"ucl_champions_league_schedule"
    },
    "https://fbref.com/en/comps/8/stats/Champions-League-Stats":{
        "stats_squads_standard":"ucl_squad_stats",
        "stats_squads_standard_for":"ucl_squad_stats_for",
        "stats_squads_standard_against":"ucl_squad_stats_against"
    },
    "https://fbref.com/en/comps/8/shooting/Champions-League-Stats":{
        "stats_squad_shooting_for" : "ucl_stats_shooting_for",
        "stats_squad_shooting_against" : "ucl_stats_shooting_against",
        "stats_shooting": "ucl_shooting_stats"
    },
    "https://fbref.com/en/comps/8/passing/Champions-League-Stats":{
        "stats_squads_passing_for": "ucl_stats_passing_for",
        "stats_squads_passing_against": "ucl_stats_passing_against",
        "stats_passing": "ucl_stats_passing"
    },
    "https://fbref.com/en/comps/8/gca/Champions-League-Stats":{
        "stats_squads_gca_for", "ucl_stats_gca_for",
        "stats_squads_gca_against", "ucl_stats_gca_against",
        "stats_gca", "ucl_stats_gca",
    },
    "https://fbref.com/en/comps/8/defense/Champions-League-Stats":{
        "stats_squads_defense_for": "ucl_stats_defense_for",
        "stats_squads_defense_against": "ucl_stats_defense_against",
         "stats_defense": "ucl_stats_defense"
    },
    "https://fbref.com/en/comps/8/possession/Champions-League-Stats":{
        "stats_squads_possession_for":"ucl_stats_possession_for",
        "stats_squads_possession_against":"ucl_stats_possession_against",
        "stats_possession":"ucl_stats_possession",
    },
    "https://fbref.com/en/comps/8/misc/Champions-League-Stats":{
        "stats_squads_misc_for": "ucl_stats_squads_misc_for", 
        "stats_squads_misc_against": "ucl_stats_squads_misc_against",
        "stats_misc": "ucl_stats_misc", 
    },
    "https://fbref.com/en/comps/8/playingtime/Champions-League-Stats":{
        "stats_squads_playing_time_for": "ucl_stats_playing_time_for",
        "stats_squads_playing_time_against": "ucl_stats_playing_time_against",
        "stats_playing_time": "ucl_stats_playing_time",
    },
    "https://fbref.com/en/comps/8/keepers/Champions-League-Stats":{
        "stats_squads_keeper_for": "ucl_stats_keeper_for",
        "stats_squads_keeper_against": "ucl_stats_keeper_against",
        "stats_keeper": "ucl_stats_keeper",
    },
    "https://fbref.com/en/comps/8/keepersadv/Champions-League-Stats":{
        "stats_squads_keeper_adv_for": "ucl_stats_keeper_adv_for",
        "stats_squads_keeper_adv_against": "ucl_stats_keeper_adv_against",
        "stats_keeper_adv": "ucl_stats_keeper_adv",
    },
    "https://fbref.com/en/comps/19/Europa-League-Stats":{
        "results2025-2026192_overall": "europa_overall_1",
        "results2025-2026190_overall": "europa_overall_2",
        
    },
    "https://fbref.com/en/comps/19/schedule/Europa-League-Scores-and-Fixtures":{
        "sched_all":"europa_sched_all"
    },
    "https://fbref.com/en/comps/19/stats/Europa-League-Stats":{
        "stats_squads_standard_for": "europa_stats_for",
         "stats_squads_standard_against": "europa_stats_against",
         "stats_standard": "europa_stats",
    },
    "https://fbref.com/en/comps/19/keepers/Europa-League-Stats":{
        "stats_squads_keeper_for":"europa_stats_keeper_for",
        "stats_squads_keeper_against":"europa_stats_keeper_against",
        "stats_keeper":"europa_stats_keeper",
    },
    "https://fbref.com/en/comps/19/keepersadv/Europa-League-Stats":{
        "stats_squads_keeper_adv_for": "europa_stats_squads_keeper_adv_for",
        "stats_squads_keeper_adv_against": "europa_stats_squads_keeper_adv_against",
        "stats_keeper_adv": "europa_stats_keeper_adv",
    },
    "https://fbref.com/en/comps/19/shooting/Europa-League-Stats":{
        "stats_squad_shooting_for": "europa_stats_squad_shooting_for",
        "stats_squad_shooting_against": "europa_stats_squad_shooting_against",
        "stats_shooting": "europa_stats_shooting"
    },
    "https://fbref.com/en/comps/19/passing/Europa-League-Stats":{
        "stats_squads_passing_for":"europa_passing_stats_for",
        "stats_squads_passing_for":"europa_passing_stats_for",
        "stats_passing":"europa_passing_stats",
    }
}

# --- Scrape and write all tables ---
for page_url, tables in page_map.items():
    print(f"\nFetching page: {page_url}")
    page_html = get_table.get_html_page(page_url)

    for table_id, table_name in tables.items():
        print(f"  → Extracting table: {table_name}")
        html = get_table.get_table_by_id(table_id)
        df = get_table.html_table_to_df(html, table_name)
        print(f"  ✅ Saved {table_name} ({len(df)} rows)")

    print(f"✅ Finished scraping all tables from {page_url}")

# --- Close Selenium driver at the end ---
get_table.driver.quit()
print("\n✅ All pages processed and driver closed.")
